# -*- coding: utf-8 -*-
"""ANÁLISIS DE PRECIO BTC. LSTM (Long Short-Term Memory)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1L2xE3ys1msyjp_014npuXJMsgrd6OdVb
"""

import yfinance as yf
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional
from tensorflow.keras.optimizers import Adam

# 1. Obtención de datos con indicadores técnicos
def get_enriched_data(symbol="BTC-USD"):
    df = yf.download(symbol, start="2020-01-01", interval="1d")

    # Indicadores Técnicos Básicos
    df['RSI'] = 100 - (100 / (1 + df['Close'].diff().gt(0).rolling(14).mean() / df['Close'].diff().lt(0).rolling(14).mean()))
    df['MA20'] = df['Close'].rolling(window=20).mean()
    df['Volatility'] = df['Close'].rolling(window=20).std()
    df['Log_Returns'] = np.log(df['Close'] / df['Close'].shift(1))

    df.dropna(inplace=True)
    return df

# 2. Preparación del dataset (Multivariante)
def create_multivariate_dataset(data, window_size=60):
    # Usamos Precio, RSI, Volatilidad y Volumen como características
    features = data[['Close', 'RSI', 'Volatility', 'Volume']].values
    target = data['Close'].values.reshape(-1, 1)

    scaler_x = MinMaxScaler(feature_range=(0, 1))
    scaler_y = MinMaxScaler(feature_range=(0, 1))

    scaled_features = scaler_x.fit_transform(features)
    scaled_target = scaler_y.fit_transform(target)

    X, y = [], []
    for i in range(window_size, len(data)):
        X.append(scaled_features[i-window_size:i])
        y.append(scaled_target[i, 0])

    return np.array(X), np.array(y), scaler_x, scaler_y

# Configuración
window_size = 60 # 60 días de historial para predecir el siguiente
df_btc = get_enriched_data()
X, y, scaler_x, scaler_y = create_multivariate_dataset(df_btc, window_size)

# Dividir en entrenamiento y prueba (80/20) sin mezclar (importante en series temporales)
split = int(len(X) * 0.8)
X_train, X_test = X[:split], X[split:]
y_train, y_test = y[:split], y[split:]

# 3. Modelo LSTM Bidireccional Robusto
model = Sequential([
    Bidirectional(LSTM(units=100, return_sequences=True), input_shape=(window_size, X.shape[2])),
    Dropout(0.2),
    LSTM(units=50, return_sequences=False),
    Dropout(0.2),
    Dense(units=25),
    Dense(units=1) # Predicción del precio
])

model.compile(optimizer=Adam(learning_rate=0.001), loss='mse')
model.fit(X_train, y_train, batch_size=32, epochs=20, validation_data=(X_test, y_test), verbose=1)

# 4. Predicción Multi-paso (7 días) y Tendencia
last_sequence = X_test[-1].reshape(1, window_size, X.shape[2])
future_preds_scaled = []

current_sequence = last_sequence.copy()
for _ in range(7):
    pred = model.predict(current_sequence, verbose=0)
    future_preds_scaled.append(pred[0, 0])

    # Actualizar la secuencia para la siguiente predicción (simplificado)
    new_row = current_sequence[0, -1, :].copy()
    new_row[0] = pred[0, 0] # Actualizamos el precio con la predicción
    current_sequence = np.append(current_sequence[:, 1:, :], [[new_row]], axis=1)

future_preds = scaler_y.inverse_transform(np.array(future_preds_scaled).reshape(-1, 1))

# 5. Resultados y Dirección (Alza/Baja)
last_price = df_btc['Close'].iloc[-1].item() # Extract the scalar value (last actual closing price)
print(f"\n--- Análisis de Tendencia ---")
# future_dates is available from cell pIVvCLHXNINm
for i, price in enumerate(future_preds):
    current_date = future_dates[i].strftime('%Y-%m-%d') # Format the date
    trend = "🚀 ALZA" if price[0] > last_price else "📉 BAJA"
    print(f"Fecha: {current_date} | Precio de Cierre Previsto: ${price[0]:,.2f} USD | Tendencia (vs día anterior): {trend}")
    last_price = price[0] # Update last_price for the next iteration

# 6. Gráfico
plt.figure(figsize=(12,6))
plt.plot(df_btc.index[-100:], df_btc['Close'].iloc[-100:], label="Histórico Reciente")
future_dates = pd.date_range(start=df_btc.index[-1] + pd.Timedelta(days=1), periods=7)
plt.plot(future_dates, future_preds, label="Predicción LSTM", marker='o', color='red')
plt.title("Predicción Robusta de Bitcoin (Multivariante + LSTM)")
plt.legend()
plt.show()

# 3. Modelo LSTM Bidireccional Robusto
model = Sequential([
    Bidirectional(LSTM(units=100, return_sequences=True), input_shape=(window_size, X.shape[2])),
    Dropout(0.2),
    LSTM(units=50, return_sequences=False),
    Dropout(0.2),
    Dense(units=25),
    Dense(units=1) # Predicción del precio
])

# Para ajustar la tasa de aprendizaje, cambia el valor de 'learning_rate' aquí
model.compile(optimizer=Adam(learning_rate=0.001), loss='mse')
model.fit(X_train, y_train, batch_size=32, epochs=20, validation_data=(X_test, y_test), verbose=1)

"""# Task
Build a Streamlit web application to visualize Bitcoin price predictions. The application should include: installation of Streamlit, a Python script (`app.py`) integrating existing functions for data acquisition, multivariate dataset creation, model loading/training, and multi-step prediction. The UI should display historical data, a prediction table, trend analysis, and a plot. Finally, provide instructions on how to run the Streamlit application locally.

## Instalar Streamlit

### Subtask:
Instalar la librería Streamlit en el entorno de ejecución para poder construir la aplicación web.

**Reasoning**:
The user wants to install the Streamlit library. I will provide a code block with the pip install command for Streamlit.
"""

!pip install streamlit

"""**Reasoning**:
The next step is to create the Streamlit application script (`app.py`). I will use the `%%writefile` magic command to create this file, incorporating all the necessary functions and Streamlit UI elements for data acquisition, model training (or loading), prediction, and visualization as described in the task.


"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# import streamlit as st
# import yfinance as yf
# import numpy as np
# import pandas as pd
# import matplotlib.pyplot as plt
# from sklearn.preprocessing import MinMaxScaler
# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import LSTM, Dense, Dropout, Bidirectional
# from tensorflow.keras.optimizers import Adam
# 
# # 1. Obtención de datos con indicadores técnicos
# @st.cache_data(ttl=3600) # Cache data for 1 hour
# def get_enriched_data(symbol="BTC-USD", start_date="2020-01-01"):
#     df = yf.download(symbol, start=start_date, interval="1d", progress=False)
# 
#     # Indicadores Técnicos Básicos
#     df['RSI'] = 100 - (100 / (1 + df['Close'].diff().gt(0).rolling(14).mean() / df['Close'].diff().lt(0).rolling(14).mean()))
#     df['MA20'] = df['Close'].rolling(window=20).mean()
#     df['Volatility'] = df['Close'].rolling(window=20).std()
#     df['Log_Returns'] = np.log(df['Close'] / df['Close'].shift(1))
# 
#     df.dropna(inplace=True)
#     return df
# 
# # 2. Preparación del dataset (Multivariante)
# def create_multivariate_dataset(data, window_size=60):
#     features = data[['Close', 'RSI', 'Volatility', 'Volume']].values
#     target = data['Close'].values.reshape(-1, 1)
# 
#     scaler_x = MinMaxScaler(feature_range=(0, 1))
#     scaler_y = MinMaxScaler(feature_range=(0, 1))
# 
#     scaled_features = scaler_x.fit_transform(features)
#     scaled_target = scaler_y.fit_transform(target)
# 
#     X, y = [], []
#     for i in range(window_size, len(data)):
#         X.append(scaled_features[i-window_size:i])
#         y.append(scaled_target[i, 0])
# 
#     return np.array(X), np.array(y), scaler_x, scaler_y
# 
# # 3. Modelo LSTM Bidireccional Robusto (defined as a function to be called)
# def build_and_train_model(X_train, y_train, X_test, y_test, window_size, num_features):
#     model = Sequential([
#         Bidirectional(LSTM(units=100, return_sequences=True), input_shape=(window_size, num_features)),
#         Dropout(0.2),
#         LSTM(units=50, return_sequences=False),
#         Dropout(0.2),
#         Dense(units=25),
#         Dense(units=1)
#     ])
#     model.compile(optimizer=Adam(learning_rate=0.001), loss='mse')
#     model.fit(X_train, y_train, batch_size=32, epochs=20, validation_data=(X_test, y_test), verbose=0)
#     return model
# 
# # Streamlit Application
# st.title("📈 Predicción de Precio de Bitcoin con LSTM")
# st.write("Esta aplicación predice el precio de Bitcoin utilizando un modelo LSTM Bidireccional y muestra las tendencias futuras.")
# 
# # Configuración de parámetros
# symbol = st.sidebar.text_input("Símbolo de la Criptomoneda", "BTC-USD")
# window_size = st.sidebar.slider("Tamaño de la Ventana (días)", 30, 90, 60)
# start_date = st.sidebar.date_input("Fecha de Inicio de Datos", value=pd.to_datetime("2020-01-01"))
# num_future_days = st.sidebar.slider("Número de Días a Predecir", 1, 15, 7)
# 
# if st.sidebar.button("Ejecutar Predicción"):
#     with st.spinner("Obteniendo y procesando datos..."):
#         df_btc = get_enriched_data(symbol=symbol, start_date=str(start_date))
# 
#     if df_btc.empty:
#         st.error("No se pudieron obtener datos para el símbolo y/o rango de fechas especificados. Por favor, verifica el símbolo.")
#     else:
#         st.subheader(f"Datos Históricos Recientes de {symbol}")
#         st.write(df_btc.tail())
# 
#         with st.spinner("Preparando dataset y entrenando el modelo..."):
#             X, y, scaler_x, scaler_y = create_multivariate_dataset(df_btc, window_size)
# 
#             # Dividir en entrenamiento y prueba (80/20) sin mezclar
#             split = int(len(X) * 0.8)
#             X_train, X_test = X[:split], X[split:]
#             y_train, y_test = y[:split], y[split:]
# 
#             model = build_and_train_model(X_train, y_train, X_test, y_test, window_size, X.shape[2])
# 
#         st.success("Modelo entrenado exitosamente!")
# 
#         # 4. Predicción Multi-paso y Tendencia
#         last_sequence = X_test[-1].reshape(1, window_size, X.shape[2])
#         future_preds_scaled = []
# 
#         current_sequence = last_sequence.copy()
#         for _ in range(num_future_days):
#             pred = model.predict(current_sequence, verbose=0)
#             future_preds_scaled.append(pred[0, 0])
# 
#             # Actualizar la secuencia para la siguiente predicción (simplificado)
#             # Asumimos que los indicadores técnicos futuros son similares a los últimos conocidos para este ejemplo
#             new_row = current_sequence[0, -1, :].copy()
#             new_row[0] = pred[0, 0] # Actualizamos el precio con la predicción
#             current_sequence = np.append(current_sequence[:, 1:, :], [[new_row]], axis=1)
# 
#         future_preds = scaler_y.inverse_transform(np.array(future_preds_scaled).reshape(-1, 1))
# 
#         # 5. Resultados y Dirección (Alza/Baja)
#         st.subheader(f"Predicción de Precio para los Próximos {num_future_days} Días")
#         last_known_price = df_btc['Close'].iloc[-1].item()
#         future_dates = pd.date_range(start=df_btc.index[-1] + pd.Timedelta(days=1), periods=num_future_days)
# 
#         predictions_df = pd.DataFrame({
#             "Fecha": future_dates.strftime('%Y-%m-%d'),
#             "Precio Previsto (USD)": [f"{p[0]:,.2f}" for p in future_preds],
#             "Tendencia": ["" for _ in future_preds]
#         })
# 
#         # Populate trend based on previous day's price
#         temp_last_price = last_known_price
#         for i in range(len(future_preds)):
#             current_predicted_price = future_preds[i][0]
#             trend = "🚀 ALZA" if current_predicted_price > temp_last_price else "📉 BAJA"
#             predictions_df.loc[i, "Tendencia"] = trend
#             temp_last_price = current_predicted_price
# 
#         st.table(predictions_df)
# 
#         st.subheader("Análisis de Tendencia")
#         for i, row in predictions_df.iterrows():
#             st.write(f"Fecha: {row['Fecha']} | Precio de Cierre Previsto: ${row['Precio Previsto (USD)']} USD | Tendencia (vs día anterior): {row['Tendencia']}")
# 
#         # 6. Gráfico
#         st.subheader("Gráfico de Precios Históricos y Predicciones")
#         fig, ax = plt.subplots(figsize=(12, 6))
#         ax.plot(df_btc.index[-window_size:], df_btc['Close'].iloc[-window_size:], label="Histórico Reciente")
#         ax.plot(future_dates, future_preds, label="Predicción LSTM", marker='o', color='red')
#         ax.set_title(f"Predicción Robusta de {symbol} (Multivariante + LSTM)")
#         ax.legend()
#         ax.grid(True)
#         st.pyplot(fig)
# 
#         st.markdown("--- Jardel Vianna (2024) --- Proyecto Final de Deep Learning")
#

"""```markdown
## Ejecutar la Aplicación Streamlit

Para ejecutar la aplicación Streamlit localmente, sigue estos pasos:

1.  **Guarda el archivo `app.py`**: Ya se ha guardado en el entorno de Colab en el paso anterior.

2.  **Abre una terminal**: Si estás en Colab, no puedes ejecutar `streamlit run` directamente como si fuera un terminal local. Sin embargo, si has descargado el archivo `app.py` a tu máquina local, puedes abrir una terminal o línea de comandos.

3.  **Navega al directorio donde guardaste `app.py`**:

    ```bash
    cd /ruta/a/tu/directorio
    ```

4.  **Ejecuta la aplicación Streamlit**: En tu terminal, ejecuta el siguiente comando:

    ```bash
    streamlit run app.py
    ```

5.  **Accede a la aplicación**: Streamlit abrirá automáticamente la aplicación en tu navegador web predeterminado (normalmente en `http://localhost:8501`). Si no se abre automáticamente, puedes copiar la URL que aparece en la terminal y pegarla en tu navegador.

**Nota Importante para Colab:**

Si deseas ejecutar la aplicación Streamlit dentro de Google Colab y verla en tu navegador (lo cual requiere una configuración adicional para exponer el puerto), necesitarías herramientas como `ngrok` o `localtunnel`. Para un despliegue local más sencillo, se recomienda descargar `app.py` y ejecutarlo en tu entorno Python local.

## Final Task

### Subtask:
Present the complete code of the Streamlit application and provide a guide on how to interact with it to visualize Bitcoin prediction results.

## Summary:

### Data Analysis Key Findings

*   **Streamlit Application Code Generated**: A comprehensive `app.py` script was created, encapsulating the entire Streamlit web application. This script integrates functions for data acquisition (using `yfinance`), calculation of technical indicators (RSI, MA20, Volatility, Log Returns), multivariate dataset preparation, training of a Bidirectional LSTM model, and multi-step price prediction.
*   **Interactive UI Components**: The Streamlit application includes interactive elements such as input fields for the cryptocurrency symbol, sliders for window size and number of prediction days, and a date selector for the data's start date, allowing users to customize the analysis.
*   **Prediction Output**: The application displays recent historical data, a detailed table of predicted prices for future days (up to 15 days), including a "Tendencia" (Trend) column indicating "ALZA" (UP) or "BAJA" (DOWN) relative to the previous day's price, and a combined plot visualizing both historical and predicted prices.
*   **Model Architecture**: The prediction model is a robust Bidirectional LSTM with two LSTM layers, Dropout for regularization, and Dense layers, compiled with the Adam optimizer and mean squared error (MSE) loss.
*   **Data Scaling**: `MinMaxScaler` is used to scale both features and target variables to a range of (0, 1) before training, which is crucial for neural network performance.

### Insights or Next Steps

*   To interact with the application, download the `app.py` file and run it locally from a terminal using `streamlit run app.py`.
*   For running the application within Google Colab and accessing it via a web browser, external tools like `ngrok` or `localtunnel` would be required to expose the local server.
"""

# Desarrollado por: [@Bookbinderr]
# App de Predicción de Criptomonedas con LSTM (streamlit-crypto-model)